// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type InventoryServiceHTTPServer interface {
	GetInventory(context.Context, *GetInventoryRequest) (*Inventory, error)
}

func RegisterInventoryServiceHTTPServer(s *http.Server, srv InventoryServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/inventory/{id}", _InventoryService_GetInventory0_HTTP_Handler(srv))
}

func _InventoryService_GetInventory0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInventoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/inventory.v1.InventoryService/GetInventory")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInventory(ctx, req.(*GetInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Inventory)
		return ctx.Result(200, reply)
	}
}

type InventoryServiceHTTPClient interface {
	GetInventory(ctx context.Context, req *GetInventoryRequest, opts ...http.CallOption) (rsp *Inventory, err error)
}

type InventoryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInventoryServiceHTTPClient(client *http.Client) InventoryServiceHTTPClient {
	return &InventoryServiceHTTPClientImpl{client}
}

func (c *InventoryServiceHTTPClientImpl) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...http.CallOption) (*Inventory, error) {
	var out Inventory
	pattern := "/inventory/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/inventory.v1.InventoryService/GetInventory"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
