server:
  http:
    addr: :8000
  grpc:
    addr: :9000
  thrift:
    addr: :10000

data:
  database:
    driver: mysql
    source: "username:password@tcp(localhost:3306)/inventory?charset=utf8mb4&parseTime=True&loc=Local"
  cache:
    redis:
      addr: "localhost:6379"

logger:
  level: info
  output: stdout

service:
  discovery:
    type: etcd
    endpoints:
      - "localhost:2379"
