http:
  addr: :8000
grpc:
  addr: :9000
thrift:
  addr: :10000
data:
  database:
    driver: mysql
    source: root:password@tcp(localhost:3306)/inventory?charset=utf8mb4&parseTime=True&loc=Local
  cache:
    network: tcp
    addr: localhost:6379
logger:
  level: info
  output: stdout
service:
  discovery:
    name: inventory-service
    endpoints:
      - http://localhost:8000
      - grpc://localhost:9000
      - thrift://localhost:10000
